sudo: required
services:
  - docker

before_install:
  - docker build -t ayushmi62/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true ayushmi62/docker_react npm run test

language: generic
